name: build_apk_and_aab_debug

on:
  pull_request:
    branches:
      - "TEST-CD-2"

jobs:
  build_apk_aab:
    name: Build debug artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 11 }
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > /home/runner/work/android-client/android-client/app/google-services.json
      - name: Build debug APK and AAB after test
        run: |
          ./gradlew test
          ./gradlew assembleDebug
          ./gradlew bundleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.aab
          path: app/build/outputs/bundle/debug/app-debug.aab
